apiVersion: apps/v1
kind: Deployment
metadata:
  name: xenopsys-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xenopsys-springboot
  template:
    metadata:
      labels:
        app: xenopsys-springboot
    spec:
      containers:
        - name: springboot
          image: rahul9198/springboot-k8s-jenkins:k8s-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata: xenopsys-springboot
  name: 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: xenopsys-springboot
